### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by azqsd** [chrippa/livestreamer#1031]
Hi,
I don't understand at all how to install livestreamer, i download it from https://pypi.python.org/pypi/livestreamer and github but after that, i have absolutely no idea of what i have to do.

**Comment by 10mins** [comment]
http://livestreamer.tanuki.se/install.html

**Comment by azqsd** [comment]
Thank you, i'm so dumb.
But now i have an another problem, after i type livestreamer.exe twitch.tv/riotgames2 worst on cmd i get:

[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/riotgames2
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__livestreamer__.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 886, in main
  File "livestreamer_cli\main.py", line 475, in handle_url
  File "livestreamer_cli\console.py", line 62, in exit
UnicodeDecodeError: 'ascii' codec can't decode byte 0x92 in position 156: ordinal not in range(128)

**Comment by StarWolf3000** [comment]
Redownload livestreamer. As you are on Windows, get the one from the Releases tab. Try it with the zipped, if the setup exe fails. Then try again with your command.

It gives me the correct output:
```
livestreamer twitch.tv/riotgames2 worst
[cli][info] Found matching plugin twitch for URL twitch.tv/riotgames2
[cli][info] Available streams: audio, high, low, medium, mobile (worst), source
(best)
[cli][info] Opening stream: mobile (hls)
```
