### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by moell9** [chrippa/livestreamer#1073]
I'm getting a broken pipe error on my Enigma2 satellite receiver. Perhaps someone can help. It's coming up after 20 to 30 minutes with a picture freeze.
Example how to play a stream:
#SERVICE 4097:0:1:0:0:0:0:0:0:0:http%3a//127.0.0.1%3a88/hlsvariant%3a//http%3a//pvr.tvip.ga/0402.m3u8 headers={"X-Forwarded-For"%3a"81.17.18.50"}:BBC One HD

Error message:
Exception happened during processing of request from ('127.0.0.1', 53886)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
  File "/usr/lib/python2.7/socket.py", line 279, in close
  File "/usr/lib/python2.7/socket.py", line 303, in flush
error: [Errno 32] Broken pipe

**Comment by moell9** [comment]
Anyone any thoughts ?

**Comment by moell9** [comment]
Please give me some help. This is concerning a lot of people using the livestreamer with a X-Forwarded stream. Without it's running perfect.

**Comment by moell9** [comment]
Is anyone here for answering questions ?

**Comment by moell9** [comment]
The problem seems not to be in Livestreamer.
These links use gstreamer as player.
gstreamer 0.1 is running without any problems; gstreamer 1.x stops working after some time with a broken pipe. 
So someone can close this ticket (perhaps with a useful comment on the problem in gstreamer).
