### ISSUE TITLE
Livestreamer Stopped working

### ISSUE THREAD

**Issue by cirrusUK** [chrippa/livestreamer#1161]
I have similar problem as  closed isssue #1149  in past few days on 3 fully updated archlinux boxes
cirrus@blade  ~  livestreamer -p mpv https://www.filmon.com/tv/cbs-reality1 low

Traceback (most recent call last):
File "/usr/bin/livestreamer", line 9, in
load_entry_point('livestreamer==1.12.2', 'console_scripts', 'livestreamer')()
File "/usr/lib/python3.5/site-packages/pkg_resources/init.py", line 568, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python3.5/site-packages/pkg_resources/init.py", line 2720, in load_entry_point
return ep.load()
File "/usr/lib/python3.5/site-packages/pkg_resources/init.py", line 2380, in load
return self.resolve()
File "/usr/lib/python3.5/site-packages/pkg_resources/init.py", line 2386, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "/usr/lib/python3.5/site-packages/livestreamer_cli/main.py", line 3, in
import requests
File "/usr/lib/python3.5/site-packages/requests/init.py", line 60, in
from .api import request, get, head, post, patch, put, delete, options
File "/usr/lib/python3.5/site-packages/requests/api.py", line 14, in
from . import sessions
File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 27, in
from .adapters import HTTPAdapter
File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 28, in
from .packages.urllib3.exceptions import NewConnectionError
ImportError: cannot import name 'NewConnectionError'

**Comment by intact** [comment]
You need python-urllib3 1.12+

**Comment by cirrusUK** [comment]
@intact  Thanks for responding, but on all 3 arch boxes this is latest [!python-urllib3](https://www.archlinux.org/packages/extra/any/python-urllib3/)  as you see it is 1.13.1-1 , i tried rolling back to previous python-urllib3 package to no avail.

**Comment by cirrusUK** [comment]
when building livestreamer-dev-git i get ...

Cloning into bare repository '/home/cirrus/build/aur/livestreamer-dev-git/livestreamer-dev-git'...
remote: Counting objects: 9122, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 9122 (delta 4), reused 0 (delta 0), pack-reused 9108
Receiving objects: 100% (9122/9122), 3.58 MiB | 769.00 KiB/s, done.
Resolving deltas: 100% (5164/5164), done.
Checking connectivity... done.
==> Validating source files with sha256sums...
    livestreamer-dev-git ... Skipped
==> Extracting sources...
  -> Creating working copy of livestreamer git repo...
Cloning into 'livestreamer-dev-git'...
done.
Switched to a new branch 'makepkg'
==> Starting pkgver()...
==> Starting build()...
running build_sphinx
creating /home/cirrus/build/aur/livestreamer-dev-git/src/livestreamer-dev-git/build
creating /home/cirrus/build/aur/livestreamer-dev-git/src/livestreamer-dev-git/build/sphinx
creating /home/cirrus/build/aur/livestreamer-dev-git/src/livestreamer-dev-git/build/sphinx/doctrees
creating /home/cirrus/build/aur/livestreamer-dev-git/src/livestreamer-dev-git/build/sphinx/man
Running Sphinx v1.3.3
Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    "Topic :: Utilities"]
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/site-packages/sphinx/setup_command.py", line 161, in run
    freshenv=self.fresh_env)
  File "/usr/lib/python3.5/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/usr/lib/python3.5/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/usr/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "conf.py", line 7, in <module>
  File "/home/cirrus/build/aur/livestreamer-dev-git/src/livestreamer-dev-git/src/livestreamer/__init__.py", line 73, in <module>
    from .api import streams
  File "/home/cirrus/build/aur/livestreamer-dev-git/src/livestreamer-dev-git/src/livestreamer/api.py", line 1, in <module>
    from .session import Livestreamer
  File "/home/cirrus/build/aur/livestreamer-dev-git/src/livestreamer-dev-git/src/livestreamer/session.py", line 12, in <module>
    from .plugin import api
  File "/home/cirrus/build/aur/livestreamer-dev-git/src/livestreamer-dev-git/src/livestreamer/plugin/api/__init__.py", line 5, in <module>
    from .http_session import HTTPSession
  File "/home/cirrus/build/aur/livestreamer-dev-git/src/livestreamer-dev-git/src/livestreamer/plugin/api/http_session.py", line 1, in <module>
    from requests import Session, __build__ as requests_version
  File "/usr/lib/python3.5/site-packages/requests/__init__.py", line 60, in <module>
    from .api import request, get, head, post, patch, put, delete, options
  File "/usr/lib/python3.5/site-packages/requests/api.py", line 14, in <module>
    from . import sessions
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 27, in <module>
    from .adapters import HTTPAdapter
  File "/usr/lib/python3.5/site-packages/requests/adapters.py", line 28, in <module>
    from .packages.urllib3.exceptions import NewConnectionError
ImportError: cannot import name 'NewConnectionError'
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by intact** [comment]
Maybe you have old urllib3 somewhere in python path.

You can try:

```
python -c "import urllib3; print(urllib3.__version__)"
```

**Comment by cirrusUK** [comment]
turns out i had installed some stuff via pip, after removing them all is well, sorry for noise.
