### ISSUE TITLE
pkg_resources.DistributionNotFound: livestreamer==1.12.2

### ISSUE THREAD

**Issue by ptkato** [chrippa/livestreamer#1166]
`livestreamer --version` output:

    ptkato@laptop:~$ livestreamer --version
    Traceback (most recent call last):
      File "/usr/bin/livestreamer", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
        working_set = WorkingSet._build_master()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
        return cls._build_from_requirements(__requires__)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
        dists = ws.resolve(reqs, Environment())
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: livestreamer==1.12.2

How can I fix that? I'm under Debian Jessie.
It's rendering me some problems at the Twitch GUI application.

**Comment by alexandersjn** [comment]
Try to install package "python-livestreamer" from the Stretch (testing) branch.

**Comment by ptkato** [comment]
Worked.
