### ISSUE TITLE
ustream.py has error on  update_chunk_info

### ISSUE THREAD

**Issue by dalepharo** [chrippa/livestreamer#1171]
running the following command on a raspberry pi:
livestreamer http://www.ustream.tv/channel/xfm-kenya best --p                                                                                                                                                           layer omxplayer --fifo

gives the output:

[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/xfm-kenya
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (uhs)
Traceback (most recent call last):
  File "/usr/local/bin/livestreamer", line 9, in <module>
    load_entry_point('livestreamer==1.12.2', 'console_scripts', 'livestreamer')()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 886, in main
    handle_url()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 491, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 378, in handle_stream
    success = output_stream(stream)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 245, in output_stream
    stream_fd, prebuffer = open_stream(stream)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 222, in open_stream
    stream_fd = stream.open()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ustreamtv.py", line 403, in open
    reader.open()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/stream/segmented.py", line 185, in open
    self.worker = self.__worker__(self)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ustreamtv.py", line 257, in __init__
    self.process_module_info()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ustreamtv.py", line 310, in process_module_info
    self.update_chunk_info(stream)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ustreamtv.py", line 319, in update_chunk_info
    chunk_range = dict(map(partial(map, int), chunk_range.items()))
ValueError: invalid literal for int() with base 10: 'dc14dae661'

**Comment by snifer1981** [comment]
I'm new to python and new to livestreamer programming, but i've made a change that solves this problem for me. I'm not sure if this is the best solution, but it's what i think the code is trying to do.

I'm attaching ustream.py (with txt extension) [ustreamtv.txt](https://github.com/chrippa/livestreamer/files/245947/ustreamtv.txt), I changed line 325 starting from this file: https://raw.githubusercontent.com/bvklim/livestreamer/92acc5a4d7f5ecbcb9c791eb8702bf995076ff1b/src/livestreamer/plugins/ustreamtv.py

**Comment by besweeet** [comment]
@snifer1981 Thanks for the updated file. I'm able to play a stream, but VLC crashes out of nowhere within 30 seconds of playback.
