### ISSUE TITLE
can't open m3u8 stream on windows 

### ISSUE THREAD

**Issue by veso266** [chrippa/livestreamer#1217]
Hi I am using livestreamer version v1.12.2 (this one exacly: https://github.com/chrippa/livestreamer/releases/download/v1.12.2/livestreamer-v1.12.2-win32-setup.exe) and it works fine but if I want to open some m3u8 stream like this one: http://62.112.54.4/hls/hayatfolk-tv.m3u8

by using livestreamer "hlsvariant://http://62.112.54.4/hls/hayatfolk-tv.m3
u8" source it gives me this error: 

Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "**main**.py", line 128, in <module>
  File "**main__livestreamer**.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 886, in main
  File "livestreamer_cli\main.py", line 475, in handle_url
  File "livestreamer_cli\console.py", line 62, in exit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 237: ordina
l not in range(128)

So now I don't know what to do 

Thanks for Anwsering and Best Regards

**Comment by flijloku** [comment]
It seems it is just a non-working playlist. For example, he does not open in VLC or MPC-player.
