### ISSUE TITLE
Problem with Twitch

### ISSUE THREAD

**Issue by Cose-3D** [chrippa/livestreamer#1237]
I've got to say I have this problem since ages in Windows 7. I have everything update, python included.

`PS> livestreamer http://www.twitch.tv/morrow
[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/morrow
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__livestreamer__.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 886, in main
  File "livestreamer_cli\main.py", line 475, in handle_url
  File "livestreamer_cli\console.py", line 62, in exit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 301: ordinal not in range(128)`

**Comment by Cose-3D** [comment]
yeah but that's a fix for ustreamer, how to I fix the Twitch one?
