### ISSUE TITLE
Streamup.com no longer works?

### ISSUE THREAD

**Issue by tp0** [chrippa/livestreamer#1256]
```
livestreamer https://streamup.com/nnnnnn best
[cli][info] Found matching plugin streamupcom for URL https://streamup.com/nnnnnn
Traceback (most recent call last):
  File "/usr/local/bin/livestreamer", line 9, in <module>
    load_entry_point('livestreamer==1.12.2', 'console_scripts', 'livestreamer')()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 897, in main
    handle_url()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 478, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 391, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugin/plugin.py", line 313, in get_streams
    return self.streams(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugin/plugin.py", line 227, in streams
    ostreams = self._get_streams()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugins/streamupcom.py", line 20, in _get_streams
    url = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Few weeks ago it still worked.

Livestreamer is latest version. I'm not sure if (before the last time I updated/reinstalled it) I was using a modified plugin (`streamupcom.py`).

**Comment by intact** [comment]
Try this version #1206

**Comment by tp0** [comment]
Thanks. Works.
