### ISSUE TITLE
Cookies Fields

### ISSUE THREAD

**Issue by grandemestre** [chrippa/livestreamer#1270]
I'm trying to play a site that has cookie sessions, how do I put all these fields:
Cookie | Value | Patch | Domain

**Comment by grandemestre** [comment]
livestreamer --http-header "Cookie=vssession=qvgacArux-KOtG2s7TUyvA14597798540782436964/v0/p7795/0c/61/fa/4633312_fa2508b68102669e370e86adcdf5e07e93d246a7/4633312-manifest.ism/?0401459778768085532509614597822444709745473gGzf1gD4vd4tUdwicYqFqw|F|527aa7ff92144743ae000157_4191fd6e-6342-41c6-811a-6f2d5baca537; optimizelyEndUserId=oeu1459473392105r0.9130382984633368; optimizelySegments=%7B%224368606843%22%3A%22none%22%2C%224322720201%22%3A%22direct%22%2C%224306972891%22%3A%22false%22%2C%224322020181%22%3A%22ff%22%7D; optimizelyBuckets=%7B%225391120919%22%3A%220%22%7D; utag_main=v_id:0153cf64a30c00482258120ddd2008049001500d0086e$_sn:1$_ss:1$_pn:1%3Bexp-session$_st:1459475192396$ses_id:1459473392396%3Bexp-session; nav13574=5dbff3fc5a3fe33e8cfb97ef109|2_231; __utma=100629313.1336473454.1459473395.1459473395.1459473395.1; __utmz=100629313.1459473395.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); glb_uid="Y9_Ekuz_fBndZ7gJt-YpTj7EJWdyOCfq5fX8WGs6Rfc="; __gads=ID=50164073f35c1854:T=1459473396:S=ALNI_MY50tB_-kVM0vp-ur-1tpRd1gUBpQ; WMPTOKEN_527aa7ff92144743ae000157=e430acff53be7918f1b02b97a5270045; locksession=df8cd05251a66fa2c2cea3e8597ca579" "hlsvariant:https://STREAM_URL" HTTP/1.1  --loglevel debug


more appears this error:

Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__livestreamer__.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 886, in main
  File "livestreamer_cli\main.py", line 471, in handle_url
  File "livestreamer_cli\main.py", line 388, in fetch_streams
  File "livestreamer\plugin\plugin.py", line 313, in get_streams
  File "livestreamer\plugin\plugin.py", line 227, in streams
  File "livestreamer\plugins\stream.py", line 54, in _get_streams
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by scottbernstein-zz** [comment]
I think your issue is that you have quotes inside of one of your cookie values (glb_uid)

Try turning the embedded quotes into %22

**Comment by grandemestre** [comment]
Deleted the code because the values of cookies can bring me a problem, is not very safe to share

I'm not sure what the problem was but solve here. I love livestreamer.
