### ISSUE TITLE
Error on Livestream live streaming video

### ISSUE THREAD

**Issue by insomniac125** [chrippa/livestreamer#1328]
I am using livestreamer in Win32. All other livestream site videos work fine for me except for this one. 

Here is what I get:
C:\livestreamer>livestreamer https://livestream.com/accounts/16829089/events/536
4094
[cli][info] Found matching plugin livestream for URL https://livestream.com/acco
unts/16829089/events/5364094
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "**main**.py", line 128, in <module>
  File "**main__livestreamer**.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 886, in main
  File "livestreamer_cli\main.py", line 471, in handle_url
  File "livestreamer_cli\main.py", line 388, in fetch_streams
  File "livestreamer\plugin\plugin.py", line 313, in get_streams
  File "livestreamer\plugin\plugin.py", line 233, in streams
  File "livestreamer\plugins\livestream.py", line 98, in _get_streams
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by FiSHYsolutions** [comment]
same issue here (using the current xubuntu-16.04-lts-repo-version):

```
bash$ livestreamer --version
livestreamer 1.12.2
bash$ livestreamer http://livestream.com/RadioMonarchsTV/events/5666624 best
[cli][info] Found matching plugin livestream for URL http://livestream.com/RadioMonarchsTV/events/5666624
Traceback (most recent call last):
  File "/usr/bin/livestreamer", line 9, in <module>
    load_entry_point('livestreamer==1.12.2', 'console_scripts', 'livestreamer')()
  File "/usr/share/livestreamer/livestreamer_cli/main.py", line 886, in main
    handle_url()
  File "/usr/share/livestreamer/livestreamer_cli/main.py", line 471, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/share/livestreamer/livestreamer_cli/main.py", line 388, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/lib/python2.7/dist-packages/livestreamer/plugin/plugin.py", line 313, in get_streams
    return self.streams(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/livestreamer/plugin/plugin.py", line 233, in streams
    ostreams = list(ostreams)
  File "/usr/lib/python2.7/dist-packages/livestreamer/plugins/livestream.py", line 98, in _get_streams
    if not swf_url.startswith("http"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by ghost** [comment]
I can confirm this problem. However, it still works that way:

```
livestreamer "akamaihd://livestream-f.akamaihd.net/1188935_5666624_7244614f78ae4753ba78fb85f9301ef2_1_2320@120036 swf=http://cdn.livestream.com/media/player.swf" best
[cli][info] Found matching plugin stream for URL akamaihd://livestream-f.akamaihd.net/1188935_5666624_7244614f78ae4753ba78fb85f9301ef2_1_2320@120036 swf=http://cdn.livestream.com/media/player.swf
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (akamaihd)
```

```
Video: MPEG4 Video (H264) 1280x720 30fps 2059kbps [V: h264 main L3.1, yuv420p, 1280x720, 2059 kb/s]
Audio: AAC 44100Hz stereo 329kbps [A: aac lc, 44100 Hz, stereo, 329 kb/s]
```
