### ISSUE TITLE
Player argument quotation mark parsing bug

### ISSUE THREAD

**Issue by bastimeyer** [chrippa/livestreamer#1337]
### Description

There seems to be a bug in the `--player` and `--player-args` parameter parser.
This bug only appears on Windows. On Linux and OSX it's working perfectly fine.
Using the latest stable release (v1.12.2) and using the installer on Windows...

See bastimeyer/livestreamer-twitch-gui#256
### Actual behavior

The parser detects different quotation marks inside strings as the beginning of another string and incorrectly requires closing quotation marks. Even if it shouldn't be required, escaping those quotes inside strings doesn't fix this issue.
### Expected behavior

This shouldn't throw errors:

`abc "foo's bar" xyz`
`abc "foo\'s bar" xyz`
`abc 'foo"s bar' xyz`
`abc 'foo\"s bar' xyz`
### Reproduction steps

``` bash
# unescaped and escaped inner '
livestreamer -p /path/to/mpv -a "--title \"abc \\\"foo's bar\\\" xyz\" {filename}" twitch.tv/CHANNEL best
livestreamer -p /path/to/mpv -a "--title \"abc \\\"foo\\\'s bar\\\" xyz\" {filename}" twitch.tv/CHANNEL best

# different wrapping quotes
livestreamer -p /path/to/mpv -a "--title \"abc 'foo\\\"s bar' xyz\" {filename}" twitch.tv/CHANNEL best
livestreamer -p /path/to/mpv -a "--title 'abc \"foo\\\'s bar\" xyz' {filename}" twitch.tv/CHANNEL best
```
### Error log

```
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__livestreamer__.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 886, in main
  File "livestreamer_cli\main.py", line 491, in handle_url
  File "livestreamer_cli\main.py", line 369, in handle_stream
  File "livestreamer_cli\main.py", line 203, in output_stream_passthrough
  File "livestreamer_cli\output.py", line 21, in open
  File "livestreamer_cli\output.py", line 121, in _open
  File "livestreamer_cli\output.py", line 131, in _open_call
  File "livestreamer_cli\output.py", line 116, in _create_arguments
  File "shlex.py", line 279, in split
  File "shlex.py", line 269, in next
  File "shlex.py", line 96, in get_token
  File "shlex.py", line 172, in read_token
ValueError: No closing quotation
```

**Comment by 0880** [comment]
```
livestreamer "https://www.twitch.tv/gsl/v/70243555" best -p "C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format \"'' -- '' -- '' -- ''"\"
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/gsl/v/70243555
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format "'' -- '' -- '' -- ''"
```

**Comment by ghost** [comment]
```
livestreamer "https://www.twitch.tv/gsl/v/70243555" best -p "C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format \"'' -- '' -- '' -- ''\""
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/gsl/v/70243555
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format "'' -- '' -- '' -- ''"
```

**Comment by bastimeyer** [comment]
~~You are passing an even number of single quotes... Remove a single `'` and see it fail. It'll then require a closing quotation mark...~~

**Edit:**
`livestreamer "https://www.twitch.tv/gsl/v/70243555" best -p "C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format \"foo \\\"bar'\\\" baz\""`

This issue is about quotations marks within other strings... Pasting working parameters isn't actually helpful.

The parser seems to ignore the escaped double-quote before bar... Then it's seeing the single quote as the beginning of a new string, but can't find an ending one.

**Comment by 0880** [comment]
```
livestreamer "https://www.twitch.tv/gsl/v/70243555" best -p "C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format \"' -- '' -- '' -- '\""
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/gsl/v/70243555
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format "' -- '' -- '' -- '"
```

**Comment by 0880** [comment]
>You are passing an even number of single quotes... Remove a single ' and see it fail. It'll then require a closing quotation mark...

```
livestreamer "https://www.twitch.tv/gsl/v/70243555" best -p "C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format \"'' -- '' -- '' -- '\""
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/gsl/v/70243555
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
```

**Comment by 0880** [comment]
>You are passing an even number of single quotes... Remove a single ' and see it fail. It'll then require a closing quotation mark...
```
livestreamer "https://www.twitch.tv/gsl/v/70243555" best -p "C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format \"'' -- '' -- '' -- '\""
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/gsl/v/70243555
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format "'' -- '' -- '' -- '"
```

**Comment by ghost** [comment]
> You are passing an even number of single quotes... Remove a single ' and see it fail. It'll then require a closing quotation mark...

```
livestreamer "https://www.twitch.tv/gsl/v/70243555" best -p "C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format \"'' -- '' -- '' -- '\""
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/gsl/v/70243555
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format "'' -- '' -- '' -- '"
```

**Comment by 0880** [comment]
Quite confusing. 

Here is another example command line (`--- "---"-" ---` instead of `--- "---'-" ---`). Maybe you can use it as workaround as long as the problem persists.

```
livestreamer "https://www.twitch.tv/gsl/v/70243555" low -p "C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format '--- \"---\"-\" ---'
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/gsl/v/70243555
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: low (hls)
[cli][info] Starting player: C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format '--- "---"-" ---'
```

**Comment by ghost** [comment]
Strangely enough, it works now.

```
livestreamer "https://www.twitch.tv/gsl/v/70243555" best -p "C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format \"--- "---'-" ---\""
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/gsl/v/70243555
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: C:\Program Files\VideoLan\VLC\VLC.exe --input-title-format "--- ---'- ---""
```
