### ISSUE TITLE
Urgent Problem: No streams found on this url : http://www.ustream.tv/channel/orocoipo

### ISSUE THREAD

**Issue by Jinux1031** [chrippa/livestreamer#1388]
I have tried to download video file from ustream, but failed.
# livestreamer ustream.tv/channel/orocoipo best

Error message: error: No streams found on this URL: http://www.ustream.tv/channel/orocoipo

I am using the latest 1.12 of livestreamer.
Are there anyone to help me?

thanks

**Comment by ghost** [comment]
```
livestreamer "http://www.ustream.tv/channel/orocoipo" best -o Ustream.flv
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/orocoipo
[cli][info] Available streams: 360p+ (worst, best)
[cli][info] Opening stream: 360p+ (uhs)
[download][Ustream.flv] Written 174.6 KB (7s @ 23.9 KB/s)
```

Pull request: #1278

**Comment by Jinux1031** [comment]
Dear 0880,

Please let me know the environment you run "livestreamer".
Python version, livestreamer version ....
thanks.

[P.S]
I have just tried to run like you taught. (python 3.4.3, livestreamer 1.12)
Error message:

jin@jin-Inspiron-3443:~/work/record_video$ livestreamer "http://www.ustream.tv/channel/orocoipo" 
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/orocoipo
Traceback (most recent call last):
  File "/usr/local/bin/livestreamer", line 9, in <module>
    load_entry_point('livestreamer==1.12.2', 'console_scripts', 'livestreamer')()
  File "/usr/local/lib/python3.4/dist-packages/livestreamer_cli/main.py", line 897, in main
    handle_url()
  File "/usr/local/lib/python3.4/dist-packages/livestreamer_cli/main.py", line 478, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/local/lib/python3.4/dist-packages/livestreamer_cli/main.py", line 391, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/local/lib/python3.4/dist-packages/livestreamer/plugin/plugin.py", line 313, in get_streams
    return self.streams(_args, *_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/livestreamer/plugin/plugin.py", line 233, in streams
    ostreams = list(ostreams)
  File "/usr/local/lib/python3.4/dist-packages/livestreamer/plugins/ustreamtv.py", line 550, in _get_live_streams
    streams = self._get_desktop_streams(channel_id)
  File "/usr/local/lib/python3.4/dist-packages/livestreamer/plugins/ustreamtv.py", line 513, in _get_desktop_streams
    provider_url = provider["url"]
KeyError: 'url'

**Comment by ghost** [comment]
Download the updated ustream plugin ([ustreamtv.py](https://raw.githubusercontent.com/bvklim/livestreamer/5db0bd748b4079a1011e2e0d238aa7844f44178b/src/livestreamer/plugins/ustreamtv.py)) and copy it into your plugins directory.

**Comment by Jinux1031** [comment]
Thanks, Dear 0880.
Everything is ok.
Let me know your contact info, such as skype id. Actually, I am interested in python projects, and I hope a lot of communications with you.
Best Regards.
