### ISSUE TITLE
Problems!

### ISSUE THREAD

**Issue by vinciusdutra** [chrippa/livestreamer#1398]
when I try to execute the program the following messages appears: 
C:\Users\Vinicius>livestreamer "http://azubu.uol.com.br/therealyetz"
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "**main**.py", line 128, in <module>
  File "**main__livestreamer**.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 886, in main
  File "livestreamer_cli\main.py", line 464, in handle_url
  File "livestreamer\session.py", line 333, in resolve_url
  File "requests\sessions.py", line 415, in head
  File "livestreamer\plugin\api\http_session.py", line 128, in request
  File "requests\sessions.py", line 349, in request
  File "requests\sessions.py", line 287, in prepare_request
  File "requests\models.py", line 287, in prepare
  File "requests\models.py", line 334, in prepare_url
  File "requests\packages\urllib3\util.py", line 397, in parse_url
requests.packages.urllib3.exceptions.LocationParseError: Failed to parse: Failed to parse: --C=:\Program Files (x86)\Livestreamer\rtmpdump\rtmpdump.exe

Please Help!

**Comment by vinciusdutra** [comment]
S A D
