### ISSUE TITLE
Ustream [stream.uhs][error] Failed to read chunk: Unknown tag type!

### ISSUE THREAD

**Issue by highflux7** [chrippa/livestreamer#1436]
Formerly working fine, ustream plugin now locates and opens stream, only to fail after several failed to read chunk messages:

/usr/local/bin/livestreamer http://www.ustream.tv/channel/duval-street best
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/duval-street
[cli][info] Available streams: 240p+ (best), mobile_240p (worst)
[cli][info] Opening stream: 240p+ (uhs)
[stream.uhs][error] Failed to read chunk 1470932233: Unknown tag type!
[stream.uhs][error] Failed to read chunk 1470932234: Unknown tag type!
[stream.uhs][error] Failed to read chunk 1470932235: Unknown tag type!
[stream.uhs][error] Failed to read chunk 1470932236: Unknown tag type!
[stream.uhs][error] Failed to read chunk 1470932237: Unknown tag type!
[stream.uhs][error] Failed to read chunk 1470932238: Unknown tag type!
[stream.uhs][error] Failed to read chunk 1470932239: Unknown tag type!
[stream.uhs][error] Failed to read chunk 1470932240: Unknown tag type!
[stream.uhs][error] Failed to read chunk 1470932241: Unknown tag type!
[stream.uhs][error] Failed to read chunk 1470932242: Unknown tag type!
[stream.uhs][error] Failed to read chunk 1470932243: Unknown tag type!
[stream.uhs][error] Failed to read chunk 1470932244: Unknown tag type!
[cli][error] Failed to read data from stream: Read timeout

**Comment by c769214** [comment]
probably you need any update version of ustreamtv.py

**Comment by highflux7** [comment]
Simply replacing the ustreamtv.py plugin with a newer version from the FurryFur repository reveals some significant code change-- failing to find name HTTPSelect.  So I cloned the entire repository, and am now faced with the following:  (of which I'm fairly clueless...)

livestreamer http://www.ustream.tv/channel/duval-street best
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/duval-street
Traceback (most recent call last):
  File "/usr/local/bin/livestreamer", line 9, in <module>
    load_entry_point('livestreamer==1.12.2', 'console_scripts', 'livestreamer')()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 961, in main
    handle_url()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 539, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 452, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugin/plugin.py", line 316, in get_streams
    return self.streams(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugin/plugin.py", line 236, in streams
    ostreams = list(ostreams)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ustreamtv.py", line 550, in _get_live_streams
    streams = self._get_desktop_streams(channel_id)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ustreamtv.py", line 513, in _get_desktop_streams
    provider_url = provider["url"]
KeyError: 'url'
