### ISSUE TITLE
Slackware64 14.2 - AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by latern4** [chrippa/livestreamer#1451]
Operating System: Slackware64 14.2
Livestreamer Version: 1.12.2 installed from [SlackBuilds](https://slackbuilds.org/repository/14.2/network/livestreamer/)
Livestreamer was installed with all mandatory dependencies including the optional ones:
RTMPDump, PyCrypto, python-librtmp
I type the following command
`
bash-4.3$ livestreamer hlsvariant://http://538hls.lswcdn.triple-it.nl/content/538tv/538tv.m3u8 best 
`
The output that i get is:
`
[cli][info] Found matching plugin stream for URL hlsvariant://http://538hls.lswcdn.triple-it.nl/content/538tv/538tv.m3u8
[cli][info] Available streams: 142k (worst), 180p, 272p, 360p, 720p (best)
[cli][info] Opening stream: 720p (hls)
Traceback (most recent call last):
  File "/usr/bin/livestreamer", line 9, in <module>
    load_entry_point('livestreamer==1.12.2', 'console_scripts', 'livestreamer')()
  File "/usr/lib64/python2.7/site-packages/livestreamer_cli/main.py", line 886, in main
    handle_url()
  File "/usr/lib64/python2.7/site-packages/livestreamer_cli/main.py", line 491, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "/usr/lib64/python2.7/site-packages/livestreamer_cli/main.py", line 378, in handle_stream
    success = output_stream(stream)
  File "/usr/lib64/python2.7/site-packages/livestreamer_cli/main.py", line 245, in output_stream
    stream_fd, prebuffer = open_stream(stream)
  File "/usr/lib64/python2.7/site-packages/livestreamer_cli/main.py", line 222, in open_stream
    stream_fd = stream.open()
  File "/usr/lib64/python2.7/site-packages/livestreamer/stream/hls.py", line 258, in open
    reader.open()
  File "/usr/lib64/python2.7/site-packages/livestreamer/stream/segmented.py", line 185, in open
    self.worker = self.__worker__(self)
  File "/usr/lib64/python2.7/site-packages/livestreamer/stream/hls.py", line 125, in __init__
    self.reload_playlist()
  File "/usr/lib64/python2.7/site-packages/livestreamer/stream/hls.py", line 138, in reload_playlist
    playlist = hls_playlist.load(res.text, res.url)
  File "/usr/lib64/python2.7/site-packages/livestreamer/stream/hls_playlist.py", line 279, in load
    return parser(base_uri).parse(data)
  File "/usr/lib64/python2.7/site-packages/livestreamer/stream/hls_playlist.py", line 245, in parse
    self.parse_line(lineno, line)
  File "/usr/lib64/python2.7/site-packages/livestreamer/stream/hls_playlist.py", line 197, in parse_line
    self.m3u8.allow_cache = self.parse_tag(line, self.parse_bool)
  File "/usr/lib64/python2.7/site-packages/livestreamer/stream/hls_playlist.py", line 147, in parse_tag
    tag, value = self.split_tag(line)
  File "/usr/lib64/python2.7/site-packages/livestreamer/stream/hls_playlist.py", line 102, in split_tag
    return match.group("tag"), match.group("value").strip()
AttributeError: 'NoneType' object has no attribute 'strip'
`

**Comment by ghost** [comment]
> `AttributeError: 'NoneType' object has no attribute 'strip'`

A quick workaround to fix this problem is to remove `.strip()` in line [102](https://github.com/chrippa/livestreamer/blob/develop/src/livestreamer/stream/hls_playlist.py#L102).

```
livestreamer "hlsvariant://http://538hls.lswcdn.triple-it.nl/content/538tv/538tv.m3u8" best
[cli][info] Found matching plugin stream for URL hlsvariant://http://538hls.lswcdn.triple-it.nl/content/538tv/538tv.m3u8
[cli][info] Available streams: 142k (worst), 180p, 272p, 360p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: "C:\Program Files (x86)\Video\MPC-HC\MPC-HC.exe"
```

```
Video: MPEG4 Video (H264) 1280x720 25fps [V: h264 main L3.1, yuv420p, 1280x720]
Audio: AAC 48000Hz stereo 130kbps [A: aac lc, 48000 Hz, stereo, 130 kb/s]
```

**Comment by intact** [comment]
or change line 99 to:

```
match = re.match("#(?P<tag>[\w-]+)(:(?P<value>.+))", line)
```

PS: btw. problem is broken playlist

**Comment by latern4** [comment]
Changing Line 99 in the file
**/usr/lib64/python2.7/site-packages/livestreamer/stream/hls_playlist.py**
to

> match = re.match("#(?P<tag>[\w-]+)(:(?P<value>.+))", line)

solved my problem.
