### ISSUE TITLE
Livestream.com URL Not Working Anymore

### ISSUE THREAD

**Issue by Spiral-King** [chrippa/livestreamer#1465]
Livestream.com changed their UI for their player and I'm guessing something else under the hood because a link I used to download no longer works.  The string I am using is as follows.

_livestreamer "http://livestream.com/accounts/4099489/events/2120235" 720p_hls -o 01.ts_

> H:>livestreamer "http://livestream.com/accounts/4099489/events/2120235" 720p_hl
> s -o 01.ts
> [cli][info] Found matching plugin livestream for URL http://livestream.com/accou
> nts/4099489/events/2120235
> Traceback (most recent call last):
>   File "<string>", line 6, in <module>
>   File "**main**.py", line 128, in <module>
>   File "**main__livestreamer**.py", line 9, in <module>
>   File "livestreamer_cli\main.py", line 886, in main
>   File "livestreamer_cli\main.py", line 471, in handle_url
>   File "livestreamer_cli\main.py", line 388, in fetch_streams
>   File "livestreamer\plugin\plugin.py", line 313, in get_streams
>   File "livestreamer\plugin\plugin.py", line 233, in streams
>   File "livestreamer\plugins\livestream.py", line 98, in _get_streams
> AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by intact** [comment]
You can try #1277

**Comment by Junior1544** [comment]
Yea, @intact is right...  I use livestreamer with a livestream.com live stream all the time, and #1277 worked perfectly for me!

hls still doesn't work right, but the normal way works great for me and I use it on a raspberry pi...

Good luck!

**Comment by Spiral-King** [comment]
Thanks for your feedback guy.  I only use livestreamer to capture this one link.  I'm not a programmer or coder so I don't know what do with what you linked you gave me.  I went to [this link](https://github.com/chrippa/livestreamer/pull/1277/commits/1c56fb27598f57a03a7a408fc606a1a8dce61607) from the link you sent me and copied the code to notepad and saved it as "livestream.py" and put it in "C:\Program Files (x86)\Livestreamer\plugins". However it didn't seem to do a anything since I'm getting the same exact error as above.

**Comment by intact** [comment]
You need [this](https://raw.githubusercontent.com/intact/livestreamer/c653539e1cc2ac185916e7680aff33558feef5f7/src/livestreamer/plugins/livestream.py) version

**Comment by scottbernstein-zz** [comment]
The problem is that on the Windows version of livestreamer you need to install the compiled version of livestream.py -- which will be titled "livestream.pyc".

Unfortunately since you say you are a non-programmer, this may be difficult for you, but this explains how to compile a .py file to a .pyc file:

http://effbot.org/pyfaq/how-do-i-create-a-pyc-file.htm

How do I create a .pyc file? - effbot.orghttp://effbot.org/pyfaq/how-do-i-create-a-pyc-file.htm
effbot.org
Python automatically compiles your script to compiled code, so called byte code, before running it. When a module is imported for the first time, or when the source ...

If I had recompiled this module myself, I would offer to email it to you, but I haven't.

Poke me if you're still in trouble after giving an honest attempt at it and if you catch me in a good mood, I'll just do it for you and email it to you.  [😊]

As a technical person, I don't need (or use) the livestreamer plugin, I just look at the source of the page and find the m3u8 URL myself.  Regardless I've found that the livestream plugin cuts out when the file hits exactly 2GB.  When I reported this as a bug, I was (correctly) told that actually the server just stops sending the stream after it hits 2GB, so it's not a bug in livestreamer.  That said, if you use the HLS stream endpoint, the same problem doesn't occur.  So I manually force it to use the HLS source.

Scott

**Comment by Spiral-King** [comment]
Thanks for your feedback guys.  I tried my best to understand what was being said in the link you sent me Scott but all the links on the page are dead! Scott, how do I private message you?  I can give you my email.

**Comment by scottbernstein-zz** [comment]
@Spiral-King are you still stuck?  If so, I will post a download link here for you.

**Comment by Spiral-King** [comment]
Yes I am.  I was trying to private message or poke you but don't know how.  Honestly I just created an account on here for this one issue.  Thanks a lot of your help in advance.  I can give you my email if you can tell me how to message you.

**Comment by scottbernstein-zz** [comment]
OK, please grab it from here as soon as you are able:

https://drive.google.com/file/d/0B_MUY9V7tRe7UWdhQnM3SUxZalk/view?usp=sharing

Also please let me know once you've grabbed it so I can remove  [😊]

**Comment by Spiral-King** [comment]
Okay I downloaded it.  Thank you.  However I'm not sure what directory I am suppose to put it in.  I put it in every folder that has files ending in ".pyc" and I still get the same error.  My default install directory is "C:\Program Files (x86)\Livestreamer".  Only one directory asked me to overwrite and existing file with the same name and I hit "Yes'.

**Comment by scottbernstein-zz** [comment]
It goes in:
C:\Program Files (x86)\livestreamer\livestreamer-1.12.2-py2.7.egg\livestreamer\plugins

**Comment by Spiral-King** [comment]
![1](https://cloud.githubusercontent.com/assets/21953329/18756301/67d613a6-80bd-11e6-9b5b-01526b1fbeae.jpg)

I put it in there and I still get this message.  I really think it has to do with something Livestreamer.com changed.... Just guessing though.

**Comment by scottbernstein-zz** [comment]
I can confirm that I am seeing the same error on this particular stream with the updated version.

**Comment by intact** [comment]
Thats old plugin, you need "new" version. :)

Delete livestream.pyc, livestream.py and download https://raw.githubusercontent.com/intact/livestreamer/c653539e1cc2ac185916e7680aff33558feef5f7/src/livestreamer/plugins/livestream.py

**Comment by Spiral-King** [comment]
OMG it worked!  Finally after 21 days!  Thank you @intact so much!  @scottbernstein also thank you for trying to help me out.  None of you had to do this but you did and I'm very grateful for both of you!  Thank you!
