### ISSUE TITLE
cant working on ubuntu16 when i finshed install 

### ISSUE THREAD

**Issue by p1020119** [chrippa/livestreamer#1477]
Traceback (most recent call last):
  File "/usr/local/bin/livestreamer", line 9, in <module>
    load_entry_point('livestreamer==1.12.2', 'console_scripts', 'livestreamer')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2235, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 3, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/**init**.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

**Comment by intact** [comment]
Your python-urllib3 is too old (you need 1.9.1-3+).
