### ISSUE TITLE
Error downloading Twitch VODs?

### ISSUE THREAD

**Issue by thejaydot** [chrippa/livestreamer#1544]
I’ve been using Livestreamer to download Twitch VODs without issue, but recently some VODs have been returning this error:

```
[cli][info] Opening stream: source (hls)
Traceback (most recent call last):
  File "/usr/local/bin/livestreamer", line 8, in <module>
    load_entry_point('livestreamer==1.12.0', 'console_scripts', 'livestreamer')()
  File "/Library/Python/2.7/site-packages/livestreamer-1.12.0-py2.7.egg/livestreamer_cli/main.py", line 886, in main
    handle_url()
  File "/Library/Python/2.7/site-packages/livestreamer-1.12.0-py2.7.egg/livestreamer_cli/main.py", line 491, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "/Library/Python/2.7/site-packages/livestreamer-1.12.0-py2.7.egg/livestreamer_cli/main.py", line 378, in handle_stream
    success = output_stream(stream)
  File "/Library/Python/2.7/site-packages/livestreamer-1.12.0-py2.7.egg/livestreamer_cli/main.py", line 245, in output_stream
    stream_fd, prebuffer = open_stream(stream)
  File "/Library/Python/2.7/site-packages/livestreamer-1.12.0-py2.7.egg/livestreamer_cli/main.py", line 222, in open_stream
    stream_fd = stream.open()
  File "/Library/Python/2.7/site-packages/livestreamer-1.12.0-py2.7.egg/livestreamer/stream/hls.py", line 254, in open
    reader.open()
  File "/Library/Python/2.7/site-packages/livestreamer-1.12.0-py2.7.egg/livestreamer/stream/segmented.py", line 185, in open
    self.worker = self.__worker__(self)
  File "/Library/Python/2.7/site-packages/livestreamer-1.12.0-py2.7.egg/livestreamer/stream/hls.py", line 121, in __init__
    self.reload_playlist()
  File "/Library/Python/2.7/site-packages/livestreamer-1.12.0-py2.7.egg/livestreamer/stream/hls.py", line 134, in reload_playlist
    playlist = hls_playlist.load(res.text, res.url)
  File "/Library/Python/2.7/site-packages/livestreamer-1.12.0-py2.7.egg/livestreamer/stream/hls_playlist.py", line 275, in load
    return parser(base_uri).parse(data)
  File "/Library/Python/2.7/site-packages/livestreamer-1.12.0-py2.7.egg/livestreamer/stream/hls_playlist.py", line 241, in parse
    self.parse_line(lineno, line)
  File "/Library/Python/2.7/site-packages/livestreamer-1.12.0-py2.7.egg/livestreamer/stream/hls_playlist.py", line 162, in parse_line
    segment = Segment(self.uri(line), extinf[0],
TypeError: 'NoneType' object has no attribute '__getitem__'
```

The command I’m using is:

`livestreamer --twitch-oauth-token [token] [URL] best -o vod.mp4`

Any help would be greatly appreciated!

**Comment by flijloku** [comment]
Maybe using streamlink https://github.com/streamlink/streamlink/releases instead livestreamer solve your problem?

**Comment by tarasis** [comment]
For me the VOD's return "No streams found on this URL ...." even though I've successfully authenticated. Will try out the streamlink suggestion.
