### ISSUE TITLE
Download exits with "MemoryError"

### ISSUE THREAD

**Issue by Xonshiz** [chrippa/livestreamer#1585]
I've been having a weird problem lately with this stream url. Livestreamer doesn't download the file and displays "MemoryError" and just right after that, it shows "Download Complete".

Here's the output : 

```
Execution Command > livestreamer.exe --verbose "hlsvariant://https://d132fumi6di
1wa.cloudfront.net/FunimationStoreFront/1594426/English/1594426_English_690559f0
-08dd-e611-80c5-0017a4776c06.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0
cHM6Ly9kMTMyZnVtaTZkaTF3YS5jbG91ZGZyb250Lm5ldC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNz
VGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDg3ODUxMDA4fX19XX0_&Signature=P2nNCZj-nkVd71y8R
t0GVxCJbMZnH0~u-Oz6sdi7l55o3Zw0sW2AM9LzN38vMWbj0Llwi1ccUrA8nmhNJm~jVfl-Qh2fafqxx
Eex1ggNtNt87ak7yPEQxjQVWtPcaQ8R0VpzT6sdDqpWGpEIY8kFh07S4DevhV8txDYClGg3iHDi2~ncm
J64B~4~oYG64i52ySazpUtkooNfKWEPfZwiGSN0Bbd8Pa4oK90ndMJ4wvd8fUOIts2s~XXVtckyJFZ8g
jnwR6Q~T0F2Gdk7hmF5EtfuMJUw~QmFNL1xjXqe8-2yk4USDmOKN-UHbdZorjMtGcWQaECVHeKVRDmfX
-Y~wA__&Key-Pair-Id=APKAIHNXECY27H4O6NIA" 720p -o "My Output File.mp4"

[cli][info] Found matching plugin stream for URL hlsvariant://https://d132fumi6d
i1wa.cloudfront.net/FunimationStoreFront/1594426/English/1594426_English_690559f
0-08dd-e611-80c5-0017a4776c06.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR
0cHM6Ly9kMTMyZnVtaTZkaTF3YS5jbG91ZGZyb250Lm5ldC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXN
zVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDg3ODUxMDA4fX19XX0_&Signature=P2nNCZj-nkVd71y8
Rt0GVxCJbMZnH0~u-Oz6sdi7l55o3Zw0sW2AM9LzN38vMWbj0Llwi1ccUrA8nmhNJm~jVfl-Qh2fafqx
xEex1ggNtNt87ak7yPEQxjQVWtPcaQ8R0VpzT6sdDqpWGpEIY8kFh07S4DevhV8txDYClGg3iHDi2~nc
mJ64B~4~oYG64i52ySazpUtkooNfKWEPfZwiGSN0Bbd8Pa4oK90ndMJ4wvd8fUOIts2s~XXVtckyJFZ8
gjnwR6Q~T0F2Gdk7hmF5EtfuMJUw~QmFNL1xjXqe8-2yk4USDmOKN-UHbdZorjMtGcWQaECVHeKVRDmf
X-Y~wA__&Key-Pair-Id=APKAIHNXECY27H4O6NIA
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__livestreamer__.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 886, in main
  File "livestreamer_cli\main.py", line 471, in handle_url
  File "livestreamer_cli\main.py", line 388, in fetch_streams
  File "livestreamer\plugin\plugin.py", line 313, in get_streams
  File "livestreamer\plugin\plugin.py", line 227, in streams
  File "livestreamer\plugins\stream.py", line 73, in _get_streams
  File "livestreamer\stream\hls.py", line 282, in parse_variant_playlist
  File "requests\models.py", line 711, in text
  File "requests\models.py", line 598, in apparent_encoding
  File "requests\packages\chardet\__init__.py", line 30, in detect
  File "requests\packages\chardet\universaldetector.py", line 128, in feed
  File "requests\packages\chardet\charsetgroupprober.py", line 64, in feed
  File "requests\packages\chardet\sjisprober.py", line 54, in feed
MemoryError
Download Complete!
```

I checked the hard drive and it has plenty of space (127 GB). If there's an error, it shouldn't show "Download complete" at the very least. Any ideas what this might be?

**Comment by cdrage** [comment]
@Xonshiz Livestreamer has been abandoned. Please try our fork of Livestreamer at http://github.com/streamlink/streamlink

**Comment by Xonshiz** [comment]
what? Livestreamer has been abandoned? omg.
But, thanks for the streamlink. I'll give it a run :)
