### ISSUE TITLE
pkg_resources.DistributionNotFound: requests>=1.0,<3.0

### ISSUE THREAD

**Issue by spvkgn** [chrippa/livestreamer#384]
Please help with this issue

```
~ $ livestreamer 
Traceback (most recent call last):
  File "/usr/local/bin/livestreamer", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=1.0,<3.0

~ $ pip search requests
requests                  - Python HTTP for Humans.
  INSTALLED: 2.2.1 (latest)
```

**Comment by noamelf** [comment]
Hi @chrippa, your solution also works for me (thanks!), but can you explain why it works?

**Comment by tjordan73** [comment]
Many thanks @chrippa, that worked for me also.

**Comment by bmurthy97** [comment]
i think ryu doesnt install properly in my system.Does anyone write the clear steps to install and if possible to remove previous ryu
