### ISSUE TITLE
I get htis everytime i try to watch a livestream on twitch.Pls help!

### ISSUE THREAD

**Issue by George234** [chrippa/livestreamer#674]
[cli][info] Found matching plugin twitch for URL twitch.tv/flosd
[cli][info] Available streams: audio, high, low, medium, mobile (worst), source
(best)
[cli][info] Opening stream: medium (hls)
[cli][info] Starting player: 'C:\Program Files\VideoLAN\VLC\vlc.exe'
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__livestreamer__.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 851, in main
  File "livestreamer_cli\main.py", line 470, in handle_url
  File "livestreamer_cli\main.py", line 357, in handle_stream
  File "livestreamer_cli\main.py", line 234, in output_stream
  File "livestreamer_cli\main.py", line 89, in create_output
  File "livestreamer_cli\output.py", line 86, in __init__
IOError: [Errno 2] No such file or directory: 'nul'

**Comment by TheRPiGuy** [comment]
@George234 What are you typing into the command line?

**Comment by eightys3v3n** [comment]
I also get this error. These are the following things I have typed into the command line to try and run it.
- "livestreamer twitch.tv/CHANNEL"
- "livestreamer --default-stream best --retry-streams 4 --retry-open 10 --stream-segment-threads 4 --twitch-oauth-token lsl1h31filc9j4bk408w372hmhewoe --ringbuffer-size 512K --hls-live-edge 2 --player-passthrough hls twitch.tv/CHANNEL"
My configuration file, http://pastebin.com/irQUcn0A
Version 1.11.1
![capture](https://cloud.githubusercontent.com/assets/8406064/5785004/fe7032ce-9d8e-11e4-8058-dfb238e3390d.JPG)

If you need anything else please ask.

**Comment by George234** [comment]
@TheRPiGuy Sorry for the late answer but i was busy...I just type the standard "livestreamer twitch.tv/CHANNEL medium"

**Comment by chrippa** [comment]
Please try the fix described here:

http://grasswiki.osgeo.org/wiki/WinGRASS_errors#The_startup_fails_with_a_IOerror:_.5BErrno_2.5D_No_such_file_or_directory_:_.27nul.27

**Comment by George234** [comment]
@chrippa  Tried it..doesnt seem to work tho.

**Comment by chrippa** [comment]
It didn't say so in the article, but you probably need to reboot aswell.

**Comment by George234** [comment]
@chrippa  Same thing happens.

**Comment by eightys3v3n** [comment]
The null service is not listed for me.
![windows-info](https://cloud.githubusercontent.com/assets/8406064/6027223/f3a26bc4-ab9d-11e4-910e-7fa89d67fc0a.JPG)
![system-info](https://cloud.githubusercontent.com/assets/8406064/6027227/f9c35ae0-ab9d-11e4-992b-3a5e48dfce6a.JPG)

**Comment by George234** [comment]
It worked for me too now that i did it again..guess i did something wrong last time..silly me :P
