### ISSUE TITLE
Another crash in 1.11.1 for windows.

### ISSUE THREAD

**Issue by supercilious** [chrippa/livestreamer#729]
Further to issue #728 I switched to VLC which worked on twitch.tv streams, but crashes livestreamer on streams from livestream.com:

[cli][info] Found matching plugin livestream for URL http://new.livestream.com/c
hess24/grenkechess
[cli][info] Available streams: 24k (worst), 270p, 270p_hls, 432p, 432p_hls, 720p
 (best), 720p_hls
[cli][info] Starting player: "C:\Program Files (x86)\VLC\vlc.exe"
[cli][info] Got HTTP request from unknown player
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__livestreamer__.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 851, in main
  File "livestreamer_cli\main.py", line 470, in handle_url
  File "livestreamer_cli\main.py", line 353, in handle_stream
  File "livestreamer_cli\main.py", line 168, in output_stream_http
UnboundLocalError: local variable 'prebuffer' referenced before assignment

**Comment by supercilious** [comment]
Just to update, I tried with the current nightly build for windows (by just unzipping the files in the archive over the existing installation), and the same error occurs, although the traceback is more detailed:

[cli][info] Found matching plugin livestream for URL http://new.livestream.com/c
hess24/grenkechess
[cli][info] Available streams: 24k (worst), 270p, 270p_hls, 432p, 432p_hls, 720p
 (best), 720p_hls
[cli][info] Starting player: "C:\Program Files (x86)\VLC\vlc.exe"
[cli][info] Got HTTP request from VLC/2.1.5 LibVLC/2.1.5
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "C:\Program Files (x86)\Livestreamer\library.zip\__main__livestreamer__.p
y", line 9, in <module>
  File "c:\program files (x86)\livestreamer\livestreamer-1.11.1-py2.7.egg\livest
reamer_cli\main.py", line 877, in main
    handle_url()
  File "c:\program files (x86)\livestreamer\livestreamer-1.11.1-py2.7.egg\livest
reamer_cli\main.py", line 489, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "c:\program files (x86)\livestreamer\livestreamer-1.11.1-py2.7.egg\livest
reamer_cli\main.py", line 372, in handle_stream
    return output_stream_http(plugin, streams)
  File "c:\program files (x86)\livestreamer\livestreamer-1.11.1-py2.7.egg\livest
reamer_cli\main.py", line 184, in output_stream_http
    read_stream(stream_fd, server, prebuffer)
UnboundLocalError: local variable 'prebuffer' referenced before assignment

**Comment by chrippa** [comment]
I pushed a potential fix (652dab1be3e80c029a9900164f67619c1c4c5b54) that should avoid the crash at least. But I'm still quite puzzled how you would end up exiting the main loop at all without a stream object.
