### ISSUE TITLE
Error when trying to use --http-cookie

### ISSUE THREAD

**Issue by scottbernstein** [chrippa/livestreamer#765]
When I try to pass any --http-cookie option, I get the following stack trace:
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__livestreamer__.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 839, in main
  File "livestreamer_cli\main.py", line 614, in setup_http_session
TypeError: 'NoneType' object is not iterable

**Comment by chrippa** [comment]
Thanks for your report, this has been fixed by 243edf1b04d2e5a648b70564338a522543e4b2a2 and will be availabe in the next release soon.
