### ISSUE TITLE
Case-sensitive command-line livestreamer

### ISSUE THREAD

**Issue by kaevne** [chrippa/livestreamer#788]
the livestreamer command seems to be case-sensitive in Windows:

Reproduce:

C:\Users\Dean>LIVESTREAMER http://www.twitch.tv/esl_csgo BEST
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 122, in <module>
zipimport.ZipImportError: can't find module '__main__LIVESTREAMER__'

Works fine in lowercase:

C:\Users\Dean>livestreamer http://www.twitch.tv/esl_csgo BEST
[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/esl_csgo
[cli][info] Available streams: audio, high, low, medium, mobile (worst), source
(best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: 'C:\Program Files (x86)\VideoLAN\VLC\vlc.exe'

**Comment by chrippa** [comment]
This is a bug in bbfreeze and not something that can be fixed on our end.
