### ISSUE TITLE
new.livestream.com problem

### ISSUE THREAD

**Issue by potentate** [chrippa/livestreamer#813]
livestreamer http://new.livestream.com/wnyw/live
[cli][info] Found matching plugin livestream for URL http://new.livestream.com/wnyw/live
[cli][info] Available streams: 270p, 270p_hls, 432p, 432p_hls, 48k (worst), 720p (best), 720p_hls
[cli][info] Opening stream: 720p (akamaihd)
Traceback (most recent call last):
  File "/usr/bin/livestreamer", line 9, in <module>
    load_entry_point('livestreamer==1.12.0', 'console_scripts', 'livestreamer')()
  File "/usr/share/livestreamer/livestreamer_cli/main.py", line 853, in main
    handle_url()
  File "/usr/share/livestreamer/livestreamer_cli/main.py", line 491, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "/usr/share/livestreamer/livestreamer_cli/main.py", line 378, in handle_stream
    success = output_stream(stream)
  File "/usr/share/livestreamer/livestreamer_cli/main.py", line 245, in output_stream
    stream_fd, prebuffer = open_stream(stream)
  File "/usr/share/livestreamer/livestreamer_cli/main.py", line 222, in open_stream
    stream_fd = stream.open()
  File "/usr/lib/python2.7/dist-packages/livestreamer/stream/akamaihd.py", line 265, in open
    return StreamIOThreadWrapper(self.session, stream.open())
  File "/usr/lib/python2.7/dist-packages/livestreamer/stream/akamaihd.py", line 111, in open
    self.handshake(self.fd)
  File "/usr/lib/python2.7/dist-packages/livestreamer/stream/akamaihd.py", line 128, in handshake
    self.process_tag(tag, exception=StreamError)
  File "/usr/lib/python2.7/dist-packages/livestreamer/stream/akamaihd.py", line 136, in process_tag
    self._on_edge(tag.data.value, exception=exception)
  File "/usr/lib/python2.7/dist-packages/livestreamer/stream/akamaihd.py", line 225, in _on_edge
    sessiontoken = self._generate_session_token(data["data64"])
  File "/usr/lib/python2.7/dist-packages/livestreamer/stream/akamaihd.py", line 189, in _generate_session_token
    return generator.generate()
  File "/usr/lib/python2.7/dist-packages/livestreamer/stream/akamaihd.py", line 33, in generate
    exception=StreamError)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/livestreamer/plugin/api/http_session.py", line 133, in request
    err=rerr))
TypeError: __str__ returned non-string (type Error)

**Comment by karlo2105** [comment]
Working fine. 

<code>
livestreamer --http-no-ssl-verify "http://new.livestream.com/wnyw/live" best
[cli][info] Found matching plugin livestream for URL http://new.livestream.com/w
nyw/live
[cli][info] Available streams: 270p, 270p_hls, 432p, 432p_hls, 48k (worst), 720p
 (best), 720p_hls
[cli][info] Opening stream: 720p (akamaihd)
[cli][info] Starting player: 'C:\Program Files\VideoLAN\VLC\vlc.exe'
[cli][info] Player closed
[cli][info] Stream ended
</code>

**Comment by potentate** [comment]
Thanks.

**Comment by breunigs** [comment]
A Debian user reported the exact same issue:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780931

I cannot reproduce locally, neither with 1.12.0 nor with 1.12.1. Instead, I get a warning about an invalid an invalid SSL setup(?):
```
$ livestreamer http://new.livestream.com/WNCT/live best                                                             
[cli][info] Found matching plugin livestream for URL http://new.livestream.com/WNCT/live
[cli][info] Available streams: 270p, 270p_hls, 432p (best), 432p_hls, 48k (worst)
[cli][info] Opening stream: 432p (akamaihd)
[cli][error] Could not open stream: Unable to open URL: https://viewerplus.livestream.com/assets/swf/hdplayer-2.0-viewerplus.swf ([SSL: CERTIFICATE_VERIFY_FAILED] certificate
```

None of the browsers complain, but curl does, so I guess it’s a certificate issue on my machine. Running livestreamer with `--http-no-ssl-verify` works as expected (i.e. plays the video).

**Comment by bonacker** [comment]
--http-no-ssl-verify fixed the problem I'd been having with all Livestream streams. Thank you. In the Livestreamer documentation for this switch it says, "Usually a bad idea, only use this if you know what you're doing." Does it say this for any other reason other than the risk of going to a site that might have a fake cert?

**Comment by chrippa** [comment]
> Does it say this for any other reason other than the risk of going to a site that might have a fake cert?

No, that's the reason.
