### ISSUE TITLE
Error:  Unexpected keyword 

### ISSUE THREAD

**Issue by mbolgiano** [chrippa/livestreamer#834]
Platform:  Windows 8.1 Enterprise
Version:  1.12.1

I'm trying to play a stream that's referenced by the URL:
http://hdaks3.aetndigital.com/z/AETN-AETV_VMS/BRAND_FYI_MAFS_161192_TVE_001_2398_60_20150327_000_S3_,4,18,13,10,7,2,1,00.mp4.csmil/manifest.f4m?hdnea=st=1428041394~exp=1428052224~acl=/*~hmac=bc4ad2ff2479d5556cd94b976f3fb135c851ea3aa0aec1ff5e0e97f915695983&g=SMGDIXEWIQCV&hdcore=3.0.3

I changed http:// to hds://, and got the error below.

<code>D:\Media\Videos>livestreamer "hds://hdaks3.aetndigital.com/z/AETN-AETV_VMS/BRAND_FYI_MAFS_161192_TVE_001_2398_60_20150327_000_S3_,4,18,13,10,7,2,1,00.mp4.csmil/
manifest.f4m?hdnea=st=1428041394~exp=1428052224~acl=/*~hmac=bc4ad2ff2479d5556cd94b976f3fb135c851ea3aa0aec1ff5e0e97f915695983 g=SMGDIXEWIQCV hdcore=3.0.3"
[cli][info] Found matching plugin stream for URL hds://hdaks3.aetndigital.com/z/AETN-AETV_VMS/BRAND_FYI_MAFS_161192_TVE_001_2398_60_20150327_000_S3_,4,18,13,10,
7,2,1,00.mp4.csmil/manifest.f4m?hdnea=st=1428041394~exp=1428052224~acl=/*~hmac=bc4ad2ff2479d5556cd94b976f3fb135c851ea3aa0aec1ff5e0e97f915695983 g=SMGDIXEWIQCV h
dcore=3.0.3
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__livestreamer__.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 886, in main
  File "livestreamer_cli\main.py", line 471, in handle_url
  File "livestreamer_cli\main.py", line 388, in fetch_streams
  File "livestreamer\plugin\plugin.py", line 313, in get_streams
  File "livestreamer\plugin\plugin.py", line 227, in streams
  File "livestreamer\plugins\stream.py", line 73, in _get_streams
  File "livestreamer\stream\hds.py", line 446, in parse_manifest
  File "requests\sessions.py", line 395, in get
  File "livestreamer\plugin\api\http_session.py", line 128, in request
TypeError: request() got an unexpected keyword argument 'g'</code>

**Comment by chrippa** [comment]
You have a space in the URL. As described in the [docs](http://docs.livestreamer.io/cli.html#playing-built-in-streaming-protocols-directly), any parameters after the URL is passed to the stream object.

In this case, HDS streams will pass any unknown parameters directly to the HTTP library requests, which throws an error about the unknown parameter.
