### ISSUE TITLE
Bug report: UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by mGeek** [chrippa/livestreamer#851]
Here is the command I run :

```
livestreamer http://games.dailymotion.com/live/x29tfh3 best
```

Output :

```
[cli][info] Found matching plugin dailymotion for URL http://games.dailymotion.com/live/x29tfh3
[cli][info] Available streams: 132p (worst), 232p, 408p, 720p, 720p+ (best)
[cli][info] Opening stream: 720p+ (hds)
[cli][info] Starting player: 'C:\Program Files (x86)\VideoLAN\VLC\vlc.exe'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 551, in __bootstrap_inner
  File "livestreamer\stream\segmented.py", line 160, in run
  File "livestreamer\stream\hds.py", line 83, in write
  File "livestreamer\stream\hds.py", line 90, in convert_fragment
  File "livestreamer\packages\flashmedia\f4v.py", line 19, in __next__
  File "livestreamer\packages\flashmedia\packet.py", line 19, in deserialize
  File "livestreamer\packages\flashmedia\box.py", line 32, in _deserialize
  File "livestreamer\packages\flashmedia\types.py", line 42, in read
  File "livestreamer\packages\flashmedia\types.py", line 274, in unpack
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 0: ordinal
not in range(128)
```

VLC opens, reads a stream for a few seconds and then closes.

```
[cli][info] Stream ended
```

I do not know what's going on with my PC, I tried the command on another computer and it works correctly.
Thank you in advance, I remain available for more information.

**Comment by chrippa** [comment]
This is really strange, the crash happens because bad data is encountered when parsing the segment, but I'm not able to reproduce this at all. Do you use a proxy, VPN or anything else that might tinker with your HTTP traffic?

**Comment by pedrobotella** [comment]
Hi! I'm facing the same problem in my computer. My network goes through a VPN but I can watch the same twitch stream without a problem in my browser. Let me know if I can be of any help!

**Comment by pedrobotella** [comment]
Hi again! I was just able to watch the stream using the windows cmd as admin.

cheers!
