### ISSUE TITLE
CrunchyrollAPIError when streaming from crunchyroll

### ISSUE THREAD

**Issue by Shukaro** [chrippa/livestreamer#864]
```
C:\WINDOWS\system32>livestreamer http://www.crunchyroll.com/i-cant-understand-wh
at-my-husband-is-saying/episode-3-husband-and-wifes-xxx-678039 high
[cli][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com
/i-cant-understand-what-my-husband-is-saying/episode-3-husband-and-wifes-xxx-678
039
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__livestreamer__.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 886, in main
  File "livestreamer_cli\main.py", line 471, in handle_url
  File "livestreamer_cli\main.py", line 388, in fetch_streams
  File "livestreamer\plugin\plugin.py", line 313, in get_streams
  File "livestreamer\plugin\plugin.py", line 227, in streams
  File "livestreamer\plugins\crunchyroll.py", line 211, in _get_streams
  File "livestreamer\plugins\crunchyroll.py", line 266, in _create_api
crunchyroll.CrunchyrollAPIError: Unauthenticated request
```

I tried several different shows and they all give the same error. My config file is as follows:
```
# Format is option=value. Lines starting with a # is considered comments
# and are ignored.

# By default livestreamer will attempt to locate VLC on your system
# and use that, but you can also specify the location of a player
# yourself.

# Important: You must use a quoted path if there are spaces in the path. This
# is because the player command is parsed like a shell command to allow
# parameters to be passed to the player.

# Here is a few examples of players:

# VLC
#player="C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"
#player="C:\Program Files\VideoLAN\VLC\vlc.exe"
# Using --file-caching is recommended, but is only supported in VLC 2.0+
#player="C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" --file-caching=5000
#player="C:\Program Files\VideoLAN\VLC\vlc.exe" --file-caching=5000

# MPC-HC, must be at least version 1.7 to be used
#player="C:\Program Files (x86)\Combined Community Codec Pack\MPC\mpc-hc.exe"

# MPlayer2
#player=C:\mplayer2\mplayer2.exe -cache 4096

# MPV
player=C:\mpv-x86_64-20150328\mpv.exe --cache=8192

# Use this if you want to transport the stream to the player via a named pipe.
#player-fifo

# Use this if you want to transport the stream to the player via HTTP.
#player-http

# Use this if you want Livestreamer to only pass a URL to your player and
# let it handle the transport of the stream itself.
# player-passthrough=http,hls,rtmp

# By default Livestreamer will close the player when stream is over.
# Use this option to let the player stay or close itself instead.
player-no-close

# Use this option if you want Livestreamer to keep trying to access
# the stream even if it goes offline or disconnects. Your player must
# support HTTP and its playlist should be set to repeat mode.
#player-continuous-http

# Show console output from the video player
verbose-player

# RTMP streams are downloaded using rtmpdump. Full path to the rtmpdump exe
# should be specified here.
rtmpdump=C:\Program Files (x86)\Livestreamer\rtmpdump\rtmpdump.exe

# Log level, default is info
#loglevel=debug

# Number of threads to use when streaming HLS streams
hls-segment-threads=3

# Number of threads to use when streaming HDS streams
hds-segment-threads=3

stream-segment-threads=3

crunchyroll-username=shukaro@gmail.com
crunchyroll-password=*******************************
```

Livestreamer version is 1.12.1 on Windows.
Adding --crunchyroll-purge-credentials to the livestreamer arguments doesn't help.

**Comment by gourdcaptain** [comment]
I'm getting the same error on Arch Linux, version 1.12.1 as well.

**Comment by Arcami** [comment]
Same in Mac OS X.

**Comment by asermax** [comment]
Looks like crunchy changed something on their PS3 API, most probably the API auth tokens. I'm following [this thread](https://forums.plex.tv/index.php/topic/73626-rel-crunchyroll-plugin/page-4) to see if they can figure out what's up with it.

**Comment by asermax** [comment]
Looks like it was something related to the API token after all.
The plex plugin (from where the livestreamer's crunchyroll plugin was based off) got updated using a different set of credentials, I'll open up a pull request to start using those as well.
