### ISSUE TITLE
What is wrong with my python/system(linux/arm/debian)?

### ISSUE THREAD

**Issue by alludus** [chrippa/livestreamer#894]
Script installed with pip and using python3.4.
Here is the log from console.

user@Nokia-N900:~$ livestreamer 
Traceback (most recent call last):
  File "/opt/python3/bin/livestreamer", line 9, in <module>
    load_entry_point('livestreamer==1.12.2', 'console_scripts', 'livestreamer')()
  File "/opt/python3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/python3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/opt/python3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/opt/python3/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/python3/lib/python3.4/site-packages/livestreamer_cli/main.py", line 17, in <module>
    from livestreamer.stream import StreamProcess
  File "/opt/python3/lib/python3.4/site-packages/livestreamer/stream/__init__.py", line 5, in <module>
    from .hds import HDSStream
  File "/opt/python3/lib/python3.4/site-packages/livestreamer/stream/hds.py", line 16, in <module>
    from .segmented import (SegmentedStreamReader,
  File "/opt/python3/lib/python3.4/site-packages/livestreamer/stream/segmented.py", line 1, in <module>
    from concurrent import futures
  File "/opt/python3/lib/python3.4/concurrent/futures/__init__.py", line 17, in <module>
    from concurrent.futures.process import ProcessPoolExecutor
  File "/opt/python3/lib/python3.4/concurrent/futures/process.py", line 55, in <module>
    from multiprocessing.connection import wait
  File "/opt/python3/lib/python3.4/multiprocessing/connection.py", line 22, in <module>
    import _multiprocessing
ImportError: No module named '_multiprocessing'

**Comment by chrippa** [comment]
It looks like your Python build have stripped out the `multiprocessing` module, perhaps to reduce file size to fit on smaller ARM devices. Unfortunately the `concurrent` module which we use heavily depend on this module.

Your options here are, either install a Python that contains the `multiprocessing` module or check if there is a extra package available that adds the module to your existing install.

**Comment by alludus** [comment]
Thank you, was suspecting something like this.
