### ISSUE TITLE
pkg_resources.DistributionNotFound: futures

### ISSUE THREAD

**Issue by crucialmomment** [chrippa/livestreamer#947]
Hello, I'm on OSX, and I am experiencing this problem when I use livestreamer:
(I'm an amateur so some guidance would be much appreciated. Thank you)

Traceback (most recent call last):
  File "/usr/local/bin/livestreamer", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Python/2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/Library/Python/2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Python/2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: futures

**Comment by crucialmomment** [comment]
Sorry, all I needed to do was just reinstall my setuptools.
